version: '3.9'
services:
  resql:
    container_name: resql
    build:
      context: .
    environment:
      - sqlms.saved-queries-dir=./templates/
    volumes:
      - ./DSL:/DSL
    ports:
      - 8082:8080
    networks:
      - resql

networks:
  resql:
    driver: bridge
